bcftools norm -m +any --threads 4 -Oz -o chim.normalized.chr1.vcf.gz chim.chr1.vcf.gz; mv chim.normalized.chr1.vcf.gz chim.chr1.vcf.gz;tabix -f chim.chr1.vcf.gz
bcftools norm -m +any --threads 4 -Oz -o chim.normalized.chr2.vcf.gz chim.chr2.vcf.gz; mv chim.normalized.chr2.vcf.gz chim.chr2.vcf.gz;tabix -f chim.chr2.vcf.gz
bcftools norm -m +any --threads 4 -Oz -o chim.normalized.chr3.vcf.gz chim.chr3.vcf.gz; mv chim.normalized.chr3.vcf.gz chim.chr3.vcf.gz;tabix -f chim.chr3.vcf.gz
bcftools norm -m +any --threads 4 -Oz -o chim.normalized.chr4.vcf.gz chim.chr4.vcf.gz; mv chim.normalized.chr4.vcf.gz chim.chr4.vcf.gz;tabix -f chim.chr4.vcf.gz
bcftools norm -m +any --threads 4 -Oz -o chim.normalized.chr5.vcf.gz chim.chr5.vcf.gz; mv chim.normalized.chr5.vcf.gz chim.chr5.vcf.gz;tabix -f chim.chr5.vcf.gz
bcftools norm -m +any --threads 4 -Oz -o chim.normalized.chr6.vcf.gz chim.chr6.vcf.gz; mv chim.normalized.chr6.vcf.gz chim.chr6.vcf.gz;tabix -f chim.chr6.vcf.gz
bcftools norm -m +any --threads 4 -Oz -o chim.normalized.chr7.vcf.gz chim.chr7.vcf.gz; mv chim.normalized.chr7.vcf.gz chim.chr7.vcf.gz;tabix -f chim.chr7.vcf.gz
bcftools norm -m +any --threads 4 -Oz -o chim.normalized.chr8.vcf.gz chim.chr8.vcf.gz; mv chim.normalized.chr8.vcf.gz chim.chr8.vcf.gz;tabix -f chim.chr8.vcf.gz
bcftools norm -m +any --threads 4 -Oz -o chim.normalized.chr9.vcf.gz chim.chr9.vcf.gz; mv chim.normalized.chr9.vcf.gz chim.chr9.vcf.gz;tabix -f chim.chr9.vcf.gz
bcftools norm -m +any --threads 4 -Oz -o chim.normalized.chr10.vcf.gz chim.chr10.vcf.gz; mv chim.normalized.chr10.vcf.gz chim.chr10.vcf.gz;tabix -f chim.chr10.vcf.gz
bcftools norm -m +any --threads 4 -Oz -o chim.normalized.chr11.vcf.gz chim.chr11.vcf.gz; mv chim.normalized.chr11.vcf.gz chim.chr11.vcf.gz;tabix -f chim.chr11.vcf.gz
bcftools norm -m +any --threads 4 -Oz -o chim.normalized.chr12.vcf.gz chim.chr12.vcf.gz; mv chim.normalized.chr12.vcf.gz chim.chr12.vcf.gz;tabix -f chim.chr12.vcf.gz
bcftools norm -m +any --threads 4 -Oz -o chim.normalized.chr13.vcf.gz chim.chr13.vcf.gz; mv chim.normalized.chr13.vcf.gz chim.chr13.vcf.gz;tabix -f chim.chr13.vcf.gz
bcftools norm -m +any --threads 4 -Oz -o chim.normalized.chr14.vcf.gz chim.chr14.vcf.gz; mv chim.normalized.chr14.vcf.gz chim.chr14.vcf.gz;tabix -f chim.chr14.vcf.gz
bcftools norm -m +any --threads 4 -Oz -o chim.normalized.chr15.vcf.gz chim.chr15.vcf.gz; mv chim.normalized.chr15.vcf.gz chim.chr15.vcf.gz;tabix -f chim.chr15.vcf.gz
bcftools norm -m +any --threads 4 -Oz -o chim.normalized.chr16.vcf.gz chim.chr16.vcf.gz; mv chim.normalized.chr16.vcf.gz chim.chr16.vcf.gz;tabix -f chim.chr16.vcf.gz
bcftools norm -m +any --threads 4 -Oz -o chim.normalized.chr17.vcf.gz chim.chr17.vcf.gz; mv chim.normalized.chr17.vcf.gz chim.chr17.vcf.gz;tabix -f chim.chr17.vcf.gz
bcftools norm -m +any --threads 4 -Oz -o chim.normalized.chr18.vcf.gz chim.chr18.vcf.gz; mv chim.normalized.chr18.vcf.gz chim.chr18.vcf.gz;tabix -f chim.chr18.vcf.gz
bcftools norm -m +any --threads 4 -Oz -o chim.normalized.chr19.vcf.gz chim.chr19.vcf.gz; mv chim.normalized.chr19.vcf.gz chim.chr19.vcf.gz;tabix -f chim.chr19.vcf.gz
bcftools norm -m +any --threads 4 -Oz -o chim.normalized.chr20.vcf.gz chim.chr20.vcf.gz; mv chim.normalized.chr20.vcf.gz chim.chr20.vcf.gz;tabix -f chim.chr20.vcf.gz
bcftools norm -m +any --threads 4 -Oz -o chim.normalized.chr21.vcf.gz chim.chr21.vcf.gz; mv chim.normalized.chr21.vcf.gz chim.chr21.vcf.gz;tabix -f chim.chr21.vcf.gz
bcftools norm -m +any --threads 4 -Oz -o chim.normalized.chr22.vcf.gz chim.chr22.vcf.gz; mv chim.normalized.chr22.vcf.gz chim.chr22.vcf.gz;tabix -f chim.chr22.vcf.gz
