bcftools norm -m +any --threads 8 -Oz -o Samoan.normalized.chr1.vcf.gz Samoan_phs000972_TOPMed_WGS_freeze.9b.chr1.hg38.vcf.gz; tabix -f Samoan.normalized.chr1.vcf.gz
bcftools norm -m +any --threads 8 -Oz -o Samoan.normalized.chr2.vcf.gz Samoan_phs000972_TOPMed_WGS_freeze.9b.chr2.hg38.vcf.gz; tabix -f Samoan.normalized.chr2.vcf.gz
bcftools norm -m +any --threads 8 -Oz -o Samoan.normalized.chr3.vcf.gz Samoan_phs000972_TOPMed_WGS_freeze.9b.chr3.hg38.vcf.gz; tabix -f Samoan.normalized.chr3.vcf.gz
bcftools norm -m +any --threads 8 -Oz -o Samoan.normalized.chr4.vcf.gz Samoan_phs000972_TOPMed_WGS_freeze.9b.chr4.hg38.vcf.gz; tabix -f Samoan.normalized.chr4.vcf.gz
bcftools norm -m +any --threads 8 -Oz -o Samoan.normalized.chr5.vcf.gz Samoan_phs000972_TOPMed_WGS_freeze.9b.chr5.hg38.vcf.gz; tabix -f Samoan.normalized.chr5.vcf.gz
bcftools norm -m +any --threads 8 -Oz -o Samoan.normalized.chr6.vcf.gz Samoan_phs000972_TOPMed_WGS_freeze.9b.chr6.hg38.vcf.gz; tabix -f Samoan.normalized.chr6.vcf.gz
bcftools norm -m +any --threads 8 -Oz -o Samoan.normalized.chr7.vcf.gz Samoan_phs000972_TOPMed_WGS_freeze.9b.chr7.hg38.vcf.gz; tabix -f Samoan.normalized.chr7.vcf.gz
bcftools norm -m +any --threads 8 -Oz -o Samoan.normalized.chr8.vcf.gz Samoan_phs000972_TOPMed_WGS_freeze.9b.chr8.hg38.vcf.gz; tabix -f Samoan.normalized.chr8.vcf.gz
bcftools norm -m +any --threads 8 -Oz -o Samoan.normalized.chr9.vcf.gz Samoan_phs000972_TOPMed_WGS_freeze.9b.chr9.hg38.vcf.gz; tabix -f Samoan.normalized.chr9.vcf.gz
bcftools norm -m +any --threads 8 -Oz -o Samoan.normalized.chr10.vcf.gz Samoan_phs000972_TOPMed_WGS_freeze.9b.chr10.hg38.vcf.gz; tabix -f Samoan.normalized.chr10.vcf.gz
bcftools norm -m +any --threads 8 -Oz -o Samoan.normalized.chr11.vcf.gz Samoan_phs000972_TOPMed_WGS_freeze.9b.chr11.hg38.vcf.gz; tabix -f Samoan.normalized.chr11.vcf.gz
bcftools norm -m +any --threads 8 -Oz -o Samoan.normalized.chr12.vcf.gz Samoan_phs000972_TOPMed_WGS_freeze.9b.chr12.hg38.vcf.gz; tabix -f Samoan.normalized.chr12.vcf.gz
bcftools norm -m +any --threads 8 -Oz -o Samoan.normalized.chr13.vcf.gz Samoan_phs000972_TOPMed_WGS_freeze.9b.chr13.hg38.vcf.gz; tabix -f Samoan.normalized.chr13.vcf.gz
bcftools norm -m +any --threads 8 -Oz -o Samoan.normalized.chr14.vcf.gz Samoan_phs000972_TOPMed_WGS_freeze.9b.chr14.hg38.vcf.gz; tabix -f Samoan.normalized.chr14.vcf.gz
bcftools norm -m +any --threads 8 -Oz -o Samoan.normalized.chr15.vcf.gz Samoan_phs000972_TOPMed_WGS_freeze.9b.chr15.hg38.vcf.gz; tabix -f Samoan.normalized.chr15.vcf.gz
bcftools norm -m +any --threads 8 -Oz -o Samoan.normalized.chr16.vcf.gz Samoan_phs000972_TOPMed_WGS_freeze.9b.chr16.hg38.vcf.gz; tabix -f Samoan.normalized.chr16.vcf.gz
bcftools norm -m +any --threads 8 -Oz -o Samoan.normalized.chr17.vcf.gz Samoan_phs000972_TOPMed_WGS_freeze.9b.chr17.hg38.vcf.gz; tabix -f Samoan.normalized.chr17.vcf.gz
bcftools norm -m +any --threads 8 -Oz -o Samoan.normalized.chr18.vcf.gz Samoan_phs000972_TOPMed_WGS_freeze.9b.chr18.hg38.vcf.gz; tabix -f Samoan.normalized.chr18.vcf.gz
bcftools norm -m +any --threads 8 -Oz -o Samoan.normalized.chr19.vcf.gz Samoan_phs000972_TOPMed_WGS_freeze.9b.chr19.hg38.vcf.gz; tabix -f Samoan.normalized.chr19.vcf.gz
bcftools norm -m +any --threads 8 -Oz -o Samoan.normalized.chr20.vcf.gz Samoan_phs000972_TOPMed_WGS_freeze.9b.chr20.hg38.vcf.gz; tabix -f Samoan.normalized.chr20.vcf.gz
bcftools norm -m +any --threads 8 -Oz -o Samoan.normalized.chr21.vcf.gz Samoan_phs000972_TOPMed_WGS_freeze.9b.chr21.hg38.vcf.gz; tabix -f Samoan.normalized.chr21.vcf.gz
bcftools norm -m +any --threads 8 -Oz -o Samoan.normalized.chr22.vcf.gz Samoan_phs000972_TOPMed_WGS_freeze.9b.chr22.hg38.vcf.gz; tabix -f Samoan.normalized.chr22.vcf.gz
